### ISSUE TITLE
NPM: Versions 0.0.342–0.0.344 does not included `/dist` directory

### ISSUE THREAD

**Issue by lewisdorigo** [scottishgovernment/pattern-library#28]
When installing the pattern library from npm using `npm install @scottish-government/pattern-library`, versions 0.0.342 up to 0.0.344 does not include the `/dist` directory.

Versions prior to 0.0.342 _do_ include that directory when installing from npm.

Can you confirm whether this is an intentional change?

I note that, in the README file, it talks about building production files using the `npm run prepublish`, however this does not work when the package is installed as a dependency of a project, as the dependencies for that script to run (e.g. webpack) are dev dependencies (as they should be), so are not included as part when installing. However, this means that I'm unable to build the production files locally.

**Comment by jsutcliffe** [comment]
Hello Lewis,

That is indeed unintentional -- thanks for calling it out. It's resolved in version 0.0.345. Sorry for any inconvenience.

- Jonathan

**Comment by lewisdorigo** [comment]
Hi Jonathan!

Thanks for confirming. :)
