### ISSUE TITLE
Links and Buttons keep :focus style after leave page and navigate back

### ISSUE THREAD

**Issue by msuperina** [scottishgovernment/pattern-library#6]
The following behaviour can only be reproduced with Firefox and appears inconsistent with Chrome and Edge.
- Navigate to https://designsystem.gov.scot/
- In the Content standards section click on Learn more
- Observe the link has :focus style
- Navigate back to https://designsystem.gov.scot/
- Observe the link still has :focus style

What is the recommended behaviour ?
If Firefox is wrong, this appears to be a bug.

Note this happens with buttons as well.

**Comment by jsutcliffe** [comment]
This is due to Firefox's implementation of Back-Forward Cache. It's arguably a helpful feature, since it helps a user continue reading a page from the point that they left it.

**Comment by msuperina** [comment]
Thank you very much for the quick response.
